version: "3.7"

networks:
  bridge: ~

services:
  client:
    container_name: Practicum-frontend
    build:
      context: .
      dockerfile: .docker/nodejs/Dockerfile
      target: preview
      # init - install deps ()
      # preview - run build version as prod
      # dev - run dev, with vite hot (entry /packages/server/index)
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./:/usr/src/app
    networks:
      - bridge
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_PORT=${POSTGRES_PORT}

#    server:
#        container_name: prakticum-server
#        image: prackicum-server
#        build:
#            context: .
#            dockerfile: Dockerfile.server
#            args:
#              SERVER_PORT: ${SERVER_PORT}
#        restart: always
#        ports:
#            - "${SERVER_PORT}:${SERVER_PORT}"
#        environment:
#          SERVER_PORT: ${SERVER_PORT}
  #
  postgres:
    image: postgres:14
    user: postgres
    container_name: Practicum-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - bridge
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data

