networks:
  bridge: ~

services:
  server:
    container_name: Prakticum-server
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
      target: prod
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "24678:24678"
    networks:
      - bridge
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      SERVER_PORT: ${SERVER_PORT}

  postgres:
    image: postgres:14
    container_name: Practicum-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - bridge
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
