name: Deploy to Server

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/falcon-tanks/falcon-tanks
            git pull origin develop
            docker image prune --force
            docker system prune --all --volumes --force
            docker-compose down --volumes --remove-orphans
            docker-compose up --build -d
